/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zfc_jnisample_MainActivity */

#ifndef _Included_com_example_zfc_jnisample_MainActivity
#define _Included_com_example_zfc_jnisample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zfc_jnisample_MainActivity
 * Method:    getStringFronC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zfc_jnisample_MainActivity_getStringFronC
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zfc_jnisample_MainActivity
 * Method:    revert
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zfc_jnisample_MainActivity_revert
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
